ethics_prefix: "ETHICS_PREFIX_"  # TODO document
datadir: "DICOM_FOLDER"  # TODO document
resultsdir: "RESULTS_FOLDER"  # TODO document

qc_status:
    skip_mriqc: False  # if True, skip MRIQC reports generation, only make QC status files
    default: False  # default value for entries in QC status files

heudiconv:
    heuristic: "HEURISTIC_SCRIPT.py"  # TODO document
    threads: 2
    mem_mb: 4000
    time_min: 60

# MRIQC options
# modify cli_args to pass additional arguments to the tool
# for example, use
#   cli_args: "-vvv"
# to increase the verbosity to debugging level
# see https://mriqc.readthedocs.io/en/stable/running.html#command-line-interface for available arguments
mriqc:
    mem_mb: 16000
    time_min: 120
    threads: 8
    cli_args: ""
